### ISSUE TITLE
[Suggestion] Basic usage instruction

### ISSUE THREAD

**Issue by NoozAbooz** [Luminoso-256/piper#2]
Hi luminoso, nobody is holding me hostage in his basement and is forcing me to make a client for your internet protocol. Could you maybe add to the README a basic example usage for the protocol? Thanks!

**Comment by Luminoso-256** [comment]
The protocol specification lays out how to send and recieve messages. Any implementation would simply follow the specification.

**Comment by torralbaa** [comment]
> nobody is holding me hostage in his basement

Sounds legit.

**Comment by NoozAbooz** [comment]
> The protocol specification lays out how to send and recieve messages. Any implementation would simply follow the specification.

But like do I compile it or something to use??? Nobody said he's gonna start harvesting my organs and selling them on the dark web to buy supplies for a Taser Keyboard v2 if I don't finish in 24 hours.

**Comment by nobody5050** [comment]
I thought I told you to be quiet

**Comment by Luminoso-256** [comment]
Which part?

piper-srv is a rust project, and can be compiled with cargo.
a reference client implementation can be found [at another repository of mine](https://github.com/Luminoso-256/piper-nest).

Both of these being rust projects, you simply install rustup/cargo, and run `cargo build` inside the cloned project dir.

**Comment by NoozAbooz** [comment]
thank you, now i shall pray my organs are still intact inside my body after the next 24 hours
