### ISSUE TITLE
Unsure how to use multiple queries in URLs

### ISSUE THREAD

**Issue by Bigjango13** [Luminoso-256/piper#4]
The spec says
```
[piper://]hostname[:port][/path[?query[=...]]]
```
But it doesn't say how to make more than one query would I use`[piper://]hostname[:port][/path[?queryOne[=...]?queryTwo[=...]]]`
or `[piper://]hostname[:port][/path[?queryOne[=...]&queryTwo[=...]]]`?

**Comment by Luminoso-256** [comment]
https://github.com/Luminoso-256/piper/commit/b9b411669a979933ff4eeb8b62ecda189097ad6a 

Has now been fixed :D

(TL;DR: it's an & between each query.)
